SAPI-462-makefile updates
companieshouse/chs-streaming-api-frontend pull request #13
Opened 2020-10-29 15:54 UTC by bpathak-ch

Updates for Mesos and Marathon
* Makefile
* routes
* startup script

2020-10-30 14:47 UTC, dlgroves-ch approved these changes

2020-11-02 10:24 UTC, dlgroves-ch requested changes

2020-11-02 10:24 UTC, dlgroves-ch commented on start.sh
> +IFS=',' read -ra BROKERS <<< "${KAFKA_STREAMING_BROKER_ADDR}"
Please remove this logic; cache-broker-url expects a single-value string.

2020-11-02 11:06 UTC, bpathak-ch commented on Makefile
> +lint: GO111MODULE=off
need to remove this line as GO111MODULE is already defined 'on' at line12

2020-11-02 12:12 UTC, bpathak-ch commented on Makefile
> +lint: GO111MODULE=off
changes reverted back as golint does not support modules

2020-11-02 13:10 UTC, dlgroves-ch requested changes
Still unnecessary logic around setting the cache broker URL in the start script.

2020-11-02 16:03 UTC, dlgroves-ch approved these changes

2020-11-02 17:01 UTC, merged