SAPI-347 : feature/integrate cache broker
companieshouse/chs-streaming-api-frontend pull request #4
Opened 2020-10-15 11:48 UTC by bpathak-ch

* Further client and broker implementation for frontend service
* Unit test updates

2020-10-15 17:06 UTC, dlgroves-ch requested changes

2020-10-15 17:06 UTC, dlgroves-ch commented on client/client.go
> +	//"sync"
Please remove commented out code

2020-10-15 17:06 UTC, dlgroves-ch commented on client/client.go
> +	//
Please remove commented out code.

2020-10-15 17:06 UTC, dlgroves-ch commented on handlers/stream.go
> +			st.logger.InfoR(req, "User disconnecting")
This event will only be received when the user has disconnected; should be "user disconnected"

2020-10-15 17:06 UTC, dlgroves-ch commented on client/client.go
> +		json.Unmarshal(line, result)
We shouldn't be doing anything with the JSON that we're consuming here; we should be outputting what we receive from chs-streaming-api-cache directly to all connected users.

2020-10-19 10:23 UTC, dlgroves-ch approved these changes

2020-10-19 12:20 UTC, kinpang-CH approved these changes

2020-10-19 14:01 UTC, merged